### ISSUE TITLE
Uncaught TypeError: vasttrafik.setAccessToken is not a function

### ISSUE THREAD

**Issue by spcsmrf** [simonbengtsson/vasttrafik-api#2]
In the ./dist/vasttrafik.js there is no method called setAccessToken defined

**Comment by simonbengtsson** [comment]
What code are you using? Did you try running the example?

**Comment by spcsmrf** [comment]
Yes I am using the example.html

**Comment by simonbengtsson** [comment]
Fixed in latest commit! Thanks for reporting!
